### ISSUE TITLE
no residual convolution

### ISSUE THREAD

**Issue by HappyCoderGS** [YuanTingHsieh/TF_TCN#5]
Hello, I have a problem, please give me your guidance.
When I run pmnist_test.py, it displays'no residual convolution'.
I feel confused about this and hope you can answer it. Thank you very much.

**Comment by YuanTingHsieh** [comment]
Hi @HappyCoderGS ,
That is a debug message and you can ignore that.

That just means that for that specific layer,
there is no residual connection.

This is because of that input channels and output channels are the same.
So residual is not required.
The line is https://github.com/YuanTingHsieh/TF_TCN/blob/master/tcn/tcn.py#L221
